language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'
before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - pip install 'pytest>=3.6' pytest-cov codecov
  - poetry install -v
script:
  - py.test --cov=cree_sro_syllabics

after_success:
  - codecov
