language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'
install:
  - pip install pytest codecov
  - pip install -e .
script:
  - py.test --cov=cree_sro_syllabics

after_success:
  - codecov
